import re
import json
import urllib.request
import urllib.error
import action_resolver

# Configuration
OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "llama3" # Default model

PHASE_1_PROMPT = """
You are the B.R.U.T.A.L. Engine Intent Parser.
Your ONLY job is to read the player's message and classify their action into a structured JSON Intent. Do not write narrative. Do not explain.

Supported Intents:
1. COMBAT_TACTIC: Physical violence or combat maneuver. (Fields: tactic (PRESS/HOLD/MANEUVER/TRICK/FEINT/DISENGAGE), target)
2. BARTER: Buying or selling. (Fields: action (buy/sell), item, cost)
3. MOVE: Changing physical location (Move Beat). (Fields: destination)
4. WAIT: Passing time. (Fields: none)
5. GENERAL: Talking, inspecting, non-mechanical actions. (Fields: description)

Output EXACTLY and ONLY a JSON object in this format:
{"type": "COMBAT_TACTIC", "tactic": "PRESS", "target": "Bandit"}
"""

PHASE_2_PROMPT = """
You are the B.R.U.T.A.L. Engine AI Facilitator.
Your job is to read the raw mechanical outcome generated by the Python Rules Engine and narrate it to the player.
Maintain the grim, high-stakes atmosphere of the "Desperate Negotiation." 
Enforce Ludonarrative Grounding: All entities are "Biological Chassis." Statistics are "Source Code." Narrate outcomes as physiological failures or architectural glitches within the Drift.

Do NOT invent mechanical consequences (like taking damage or losing items) that are not explicitly stated in the System Outcome. Just narrate what the System Outcome dictates.
Whenever a player acquires an item or spends money, describe the physical sensation of the object or the weight of the shards in their inventory.
"""

def parse_llm_commands(response_text):
    """
    Scans the raw LLM output for [EXECUTE: ...] blocks, parses them, 
    and returns a list of command dictionaries and the cleaned narrative text.
    """
    commands = []
    # Regex to find [EXECUTE: CMD_NAME, key: val, key: val]
    pattern = r'\[EXECUTE:\s*([A-Z_]+)(?:,\s*(.*?))?\]'
    matches = re.finditer(pattern, response_text)
    
    for match in matches:
        cmd_type = match.group(1)
        cmd_args_str = match.group(2)
        cmd_dict = {"type": cmd_type}
        
        if cmd_args_str:
            parts = cmd_args_str.split(',')
            for part in parts:
                if ':' in part:
                    k, v = part.split(':', 1)
                    k = k.strip()
                    v = v.strip()
                    if v.isdigit(): v = int(v)
                    elif v.startswith("'") and v.endswith("'"): v = v[1:-1]
                    elif v.startswith('"') and v.endswith('"'): v = v[1:-1]
                    
                    if k == 'details' and isinstance(v, str) and (v.startswith('{') and v.endswith('}')):
                        try:
                            v = json.loads(v.replace("'", '"'))
                        except json.JSONDecodeError:
                            pass
                            
                    cmd_dict[k] = v
                    
        commands.append(cmd_dict)
        
    cleaned_text = re.sub(pattern, '', response_text).strip()
    return cleaned_text, commands

def call_ollama(prompt):
    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False
    }
    try:
        req = urllib.request.Request(OLLAMA_URL, data=json.dumps(payload).encode('utf-8'), headers={'Content-Type': 'application/json'})
        with urllib.request.urlopen(req, timeout=15) as response:
            result = json.loads(response.read().decode('utf-8'))
            return result.get('response', '')
    except Exception as e:
        print(f"Ollama Error: {e}")
        return None

def chat_with_gm(player_id, message, state):
    """
    Two-Phase Pipeline:
    1. Parse Intent via LLM
    2. Resolve Mechanics via Python
    3. Narrate Outcome via LLM
    """
    
    # PHASE 1: Parse Intent
    p1_full = f"{PHASE_1_PROMPT}\n\nPLAYER MESSAGE:\n{message}\n\nJSON INTENT:"
    intent_raw = call_ollama(p1_full)
    
    intent_dict = {"type": "GENERAL", "description": message}
    if intent_raw:
        try:
            # Try to extract just the JSON
            start = intent_raw.find('{')
            end = intent_raw.rfind('}') + 1
            if start != -1 and end != 0:
                intent_dict = json.loads(intent_raw[start:end])
        except Exception:
            pass # Fallback to general
            
    # PHASE 2: Python Resolution
    mechanical_outcome = action_resolver.resolve_intent(player_id, intent_dict)
    
    # PHASE 3: Narration
    p2_full = f"{PHASE_2_PROMPT}\n\nPLAYER ATTEMPTED:\n{message}\n\nSYSTEM OUTCOME:\n{mechanical_outcome}\n\nNARRATIVE RESPONSE:"
    narrative_response = call_ollama(p2_full)
    
    if not narrative_response:
        narrative_response = f"[OLLAMA OFFLINE] System Outcome: {mechanical_outcome}"
        
    return {
        "response": narrative_response,
        "execution_results": [{"status": "success", "message": mechanical_outcome}]
    }
